-- 01_schema.sql
-- Extensions + core tables (raw scrape + normalisation storage)
-- Case insensitive text
CREATE EXTENSION IF NOT EXISTS citext;

-- Fuzzy matching
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- Unaccented text
CREATE EXTENSION IF NOT EXISTS unaccent;

-- Raw dump from scraping
CREATE TABLE IF NOT EXISTS scraped_products(
  product_id bigserial PRIMARY KEY, -- 1,2,3,4...
  category citext NOT NULL, -- 'protein' | 'creatine'
  retailer citext NOT NULL, -- 'xplosiv'
  brand_scraped citext NOT NULL,
  name_scraped citext NOT NULL,
  flavours_scraped citext[] NOT NULL DEFAULT '{}'::citext[],
  weight_grams integer, -- unit: grams
  amount_cents integer NOT NULL, -- unit: cents
  currency_scraped citext NOT NULL, -- 'NZD'
  url citext NOT NULL,
  in_stock boolean NOT NULL,
  scraped_at timestamptz NOT NULL DEFAULT now(),
  json jsonb
);


/* Brand & Flavour normalisation storage and processing */
---------------------------------------------------------
--  brands_collection
-- brand_id | brand_normalised
-- ---------+-------------------
--  1       | optimum nutrition
--  2       | musashi
--  3       | balance
--
--  brands_alias
-- brand_scraped       | brand_id
-- --------------------+---------
-- optimum nutrition   | 1
-- musashi             | 2
-- musahi              | 2
-- balance             | 3
--
--  flavours_collection
-- flavour_id | flavour_normalised
-- -----------+---------------------
--  1         | choc
--  2         | vanilla
--  3         | strawberry
--
--  flavours_alias
-- flavour_scraped | flavour_id
-- ----------------+-----------
-- chocolate       | 1
-- choc            | 1
-- chocolte        | 1
-- vanilla         | 2
-- vanila          | 2
-- strawberry      | 3
CREATE TABLE IF NOT EXISTS brands_collection(
  brand_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand_normalised citext UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS brands_alias(
  brand_scraped citext PRIMARY KEY,
  brand_id bigint NOT NULL REFERENCES brands_collection(brand_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS flavours_collection(
  flavour_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  flavour_normalised citext UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS flavours_alias(
  flavour_scraped citext PRIMARY KEY,
  flavour_id bigint NOT NULL REFERENCES flavours_collection(flavour_id) ON DELETE CASCADE
);


/* Product normalisation storage and mapping */
-----------------------------------------------
CREATE TABLE IF NOT EXISTS products_collection(
  product_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand_id bigint NOT NULL REFERENCES brands_collection(brand_id) ON DELETE CASCADE,
  product_normalised citext NOT NULL,
  UNIQUE (brand_id, product_normalised)
);

CREATE TABLE IF NOT EXISTS product_alias(
  brand_id bigint NOT NULL REFERENCES brands_collection(brand_id) ON DELETE CASCADE,
  name_normalised citext NOT NULL,
  name_id bigint NOT NULL REFERENCES products_collection(product_id) ON DELETE CASCADE,
  PRIMARY KEY (brand_id, name_normalised)
);

-- Price history across daily snapshots
CREATE TABLE IF NOT EXISTS price_history(
  id bigserial PRIMARY KEY,
  category citext NOT NULL, -- 'protein' | 'creatine'
  product_id bigint NOT NULL,
  weight_grams integer,
  retailer citext NOT NULL,
  price integer NOT NULL, -- cents
  currency citext NOT NULL,
  snapshot_date date NOT NULL DEFAULT CURRENT_DATE
);

-- 1 row per (category × product × size × retailer × entry date)
ALTER TABLE price_history
  ADD CONSTRAINT price_history_unique_per_entry UNIQUE (category, product_id, weight_grams, retailer, snapshot_date);

