-- 01_schema.sql
-- Extensions + core tables (raw scrape + normalisation storage)
CREATE EXTENSION IF NOT EXISTS citext;

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE EXTENSION IF NOT EXISTS unaccent;

-- Raw dump from scraping
CREATE TABLE IF NOT EXISTS scraped_products(
  product_id bigserial PRIMARY KEY,
  category citext NOT NULL,
  retailer citext NOT NULL,
  brand_scraped citext NOT NULL,
  name_scraped citext NOT NULL,
  flavours_scraped citext[] NOT NULL DEFAULT '{}'::citext[],
  weight_grams integer,
  amount_cents integer NOT NULL,
  currency_scraped citext NOT NULL,
  url citext NOT NULL,
  in_stock boolean NOT NULL,
  scraped_at timestamptz NOT NULL DEFAULT now(),
  json jsonb
);

-- Brand & Flavour normalisation storage and processing
CREATE TABLE IF NOT EXISTS brands_collection(
  brand_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand_normalised citext UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS brands_alias(
  brand_scraped citext PRIMARY KEY,
  brand_id bigint NOT NULL REFERENCES brands_collection(brand_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS flavours_collection(
  flavour_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  flavour_normalised citext UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS flavours_alias(
  flavour_scraped citext PRIMARY KEY,
  flavour_id bigint NOT NULL REFERENCES flavours_collection(flavour_id) ON DELETE CASCADE
);

-- Product normalisation storage and mapping
CREATE TABLE IF NOT EXISTS products_collection(
  product_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand_id bigint NOT NULL REFERENCES brands_collection(brand_id) ON DELETE CASCADE,
  product_normalised citext NOT NULL,
  UNIQUE (brand_id, product_normalised)
);

CREATE TABLE IF NOT EXISTS product_alias(
  brand_id bigint NOT NULL REFERENCES brands_collection(brand_id) ON DELETE CASCADE,
  name_normalised citext NOT NULL,
  name_id bigint NOT NULL REFERENCES products_collection(product_id) ON DELETE CASCADE,
  PRIMARY KEY (brand_id, name_normalised)
);

-- Price history across daily snapshots
CREATE TABLE IF NOT EXISTS price_history(
  id bigserial PRIMARY KEY,
  category citext NOT NULL,
  product_id bigint NOT NULL,
  weight_grams integer,
  retailer citext NOT NULL,
  price integer NOT NULL,
  currency citext NOT NULL,
  snapshot_date date NOT NULL DEFAULT CURRENT_DATE
);

